services:
  - type: web
    name: smart-library
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "from app import create_app, db; App=create_app(); App.app_context().push(); db.create_all()" && python seed_data.py && gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: library-db
          property: connectionString

databases:
  - name: library-db
    databaseName: library
    user: library_user
    plan: free
