services:
  - type: web
    name: smart-library
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x render_start.sh && ./render_start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: library-db
          property: connectionString

databases:
  - name: library-db
    databaseName: library
    user: library_user
    plan: free
